{
 "title": "MongoDB (imported)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Open connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host:$tag_state $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "mongodb_commands_per_sec",
     "query": "SELECT mean(\"open_connections\") AS \"open-connections\" FROM \"mongodb\" WHERE \"host\" =~ /$server/ AND $timeFilter GROUP BY time($interval),*",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mongodb Active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host:$tag_state $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "state", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mongodb_active_reads",
     "query": "SELECT mean(\"active_reads\") as \"reads\",mean(\"active_writes\") as \"writes\" FROM \"mongodb\" WHERE \"host\" =~ /$server/ AND $timeFilter GROUP BY time($interval), \"host\", \"state\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host:$tag_state $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "mongodb_commands_per_sec",
     "query": "SELECT mean(\"net_in_bytes\") AS \"in\",mean(\"net_out_bytes\") AS \"out\" FROM \"mongodb\" WHERE \"host\" =~ /$server/ AND $timeFilter GROUP BY time($interval),*",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ReplicaSet Commands",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host:$tag_state $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "mongodb_commands_per_sec",
     "query": "SELECT mean(\"repl_commands_per_sec\") AS \"commands\",mean(\"repl_deletes_per_sec\") AS \"deletes\",mean(\"repl_getmores_per_sec\") AS \"getmores\",mean(\"repl_inserts_per_sec\") AS \"inserts\",mean(\"repl_queries_per_sec\") AS \"queries\",mean(\"repl_updates_per_sec\") AS \"updates\" FROM \"mongodb\" WHERE \"host\" =~ /$server/ AND $timeFilter GROUP BY time($interval),*",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host:$tag_state $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "mongodb_commands_per_sec",
     "query": "SELECT mean(\"commands_per_sec\") AS \"commands\",mean(\"deletes_per_sec\") AS \"deletes\",mean(\"flushes_per_sec\") AS \"flushes\",mean(\"getmores_per_sec\") AS \"getmores\",mean(\"inserts_per_sec\") AS \"inserts\",mean(\"updates_per_sec\") AS \"updates\" FROM \"mongodb\" WHERE \"host\" =~ /$server/ AND $timeFilter GROUP BY time($interval),*",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host:$tag_state $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "mongodb_commands_per_sec",
     "query": "SELECT mean(\"queued_reads\") AS \"reads\",mean(\"queued_writes\") AS \"writes\" FROM \"mongodb\" WHERE \"host\" =~ /$server/ AND $timeFilter GROUP BY time($interval),*",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host:$tag_state $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "mongodb_commands_per_sec",
     "query": "SELECT mean(\"mapped_megabytes\") AS \"mapped\",mean(\"non-mapped_megabytes\") AS \"non-mapped\",mean(\"resident_megabytes\") AS \"resident\",mean(\"vsize_megabytes\") AS \"vsize\" FROM \"mongodb\" WHERE \"host\" =~ /$server/ AND $timeFilter GROUP BY time($interval),*",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host:$tag_state $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "mongodb_commands_per_sec",
     "query": "SELECT mean(\"page_faults_per_sec\") AS \"page-faults\" FROM \"mongodb\" WHERE \"host\" =~ /$server/ AND $timeFilter GROUP BY time($interval),*",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}